### ISSUE TITLE
Consider removing the pkl format option

### ISSUE THREAD

**Issue by dglazkov** [dglazkov/polymath#24]
- [x] Investigate the size difference between pkl and json

**Comment by jkomoros** [comment]
For my export of ~6k cards of content, the `pkl` is 107MB and the json is 304MB.

That's a significant enough difference that maybe it is worth it to keep it around, especially since it's not too much overhead to maintain.

Perhaps we just make json the default format (since it's easier to tweak and inspect) and document when you might use .pkl?

**Comment by dglazkov** [comment]
Crazy idea: encode embeddings the way they are encoded in a query: base64 float array. I wonder how much savings that would offer?

**Comment by jkomoros** [comment]
9b4f0543207c4e65eb77f9751efbe285080a5409 and c8002308e8875934eee6c58a08d2cbb66d325171 were part of moving to b64, and saving tons of space

**Comment by jkomoros** [comment]
- [x] Create a save_library(library, filename, format=None), which encapsulates the detection of filetype by the filename extension, falling back to format='json'. Now that the in-memory representation of libraries is no longer directly serializable there need to be a bit more logic.
